export const programmingLanguages = {
    TypeScript: '/typescript.svg',
    JavaScript: '/javascript.svg',
    Cpp: '/c++.svg',
    Python: '/python.svg',
    Java: '/java.svg',
    Go: '/go.svg',
    Ruby: '/ruby.svg',
    PHP: '/php.svg',
    Swift: '/swift.svg',
    Rust: '/rust.svg',
    Kotlin: '/kotlin.svg',
    CSS: '/css.svg',
    HTML: '/html.svg',
    Shell: '/gnu_bash.svg',
    Bash: '/gnu_bash.svg',
    C: '/c.svg',
    'C#': '/csharp.svg',
    Vue: '/vuejs.svg',
    'Jupyter Notebook': '/jupyter.svg',
};